// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wfdyvvbscovstklgynhj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmZHl2dmJzY292c3RrbGd5bmhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MjM5NDEsImV4cCI6MjA2NzE5OTk0MX0.OOIHcnwl6roxft4swb0qHGlZ7yAxyP1iWHsMvbC3loM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});